-- Table: public.certificate

-- DROP TABLE IF EXISTS public.certificate;

CREATE TABLE IF NOT EXISTS public.certificate
(
    id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "profileId" int NOT NULL,
    issuer character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "issuerId" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "date" timestamp without time zone NOT NULL,
    CONSTRAINT certificate_pkey PRIMARY KEY (id),
    CONSTRAINT "certificate_profileId_fkey" FOREIGN KEY ("profileId")
        REFERENCES public.profile (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
