-- Table: public.experience

-- DROP TABLE IF EXISTS public.experience;

CREATE TABLE IF NOT EXISTS public.experience
(
    id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "profileId" int NOT NULL,
    company character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "companyId" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "startDate" timestamp without time zone NOT NULL,
    "endDate" timestamp without time zone NULL,
    CONSTRAINT experience_pkey PRIMARY KEY (id),
    CONSTRAINT "experience_profileId_fkey" FOREIGN KEY ("profileId")
        REFERENCES public.profile (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
