-- Table: public.language

-- DROP TABLE IF EXISTS public.language;

CREATE TABLE IF NOT EXISTS public.language
(
    id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code character varying(5) COLLATE pg_catalog."default" NOT NULL,
    level smallint NOT NULL,
    CONSTRAINT language_pkey PRIMARY KEY (id, code),
    CONSTRAINT language_id_fkey FOREIGN KEY (id)
        REFERENCES public.profile (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
